export type LinkType = {
  name: string;
  href: string;
};

export type LinksCollection = {
  id: string;
  title: string;
  links: LinkType[];
};

export type NavbarLink = {
  id: string;
  name: string;
  href: string;
};

export type HeroImagesType = {
  // Set the id type to number for easy index calculation
  id: number;
  description: string;
  src: string;
  href: string;
}[];

export type ProductType = {
  // _id is auto generated by Sanity
  _id: string;
  title: string;
  price: number;
  price_id: string;
  rating: number;
  comments: number;
  delivery: string;
  stock: number;
  overview: { name: string; value: string }[];
  features?: string[];
  images: string[];
  description?: string[];
  slug: { current: string };
};

export type OrderDataType = {
  amount: number;
  items: {
    quantity: number;
    id: string;
    price: string;
  }[];
  createdAt: string;
  customer: { name: string };
};

export type OrderType = {
  id: string;
  data: OrderDataType;
};
